resourced/_posts/2013-09-25-penn-state-university-redesign.md
Updated the link in the markdown file
=> corrected the broken link

_sass/_todo.scss
=> Add padding between list numbers and actual text

blogging_about/_posts/2013-11-2-how-to-contribute.md
We came across this issue today, thinking it might be helpful for future contributors.
=> Adding Jon's link to help out when using Windows

_config.yml, _includes/navigation.html, _layouts/home.html, articles.html, css/main.css, css/main.scss, index.html, js/main.js, news.html, resourced/_posts/2013-10-07-daniel-mall-bitchcast.md, resourced/_posts/2013-10-09-brad_frost-on-unfinished-business.md, resourced/_posts/2013-10-09-garthdb-on-the-east-wing.md, resources.html
Made a stab at a nav bar in the interim before redesigning the site to get the Resources on a new page to be organized. (I think it might also be a good idea to potentially have a news page for announcements when people talk about designopen.org?)
=> Nav + Resources Page

README.md, _layouts/post.html, _layouts/using-github-for-design-collaboration.html, _sass/_todo.scss
Very minor changes -- double checking a11y.com checklist to close #118
=> a11y checklist compliant

_sass/_header.scss
Fixes also alrticles, they also weren't centented
=> content centered

resources/_posts/2015-03-19-getting-traction-for-an-open-source-project.md
**URL:** http://kimmobrunfeldt.github.io/get-traction-open-source/
**Category:** tutorials
**Submitted by:** [@brennannovak](http://twitter.com/brennannovak)
Great slideshow about all the stuff (around the code) needed to make an open source project successful!
=> Add resource: Getting Traction for an Open Source Project

resources/_posts/2015-07-7-design-in-tech-2015.md
**URL:** http://www.kpcb.com/blog/design-in-tech-report-2015
**Category:** philosophy
**Submitted by:** [@winterdamsel](http://twitter.com/winterdamsel)
"Design is only needed to make things look pretty" is such an outdated thought in the Tech industry and if you're not totally convinced and need some more numbers, Maeda's report will make you a believer.
=> Add resource: Design In Tech 2015

resources/_posts/2015-04-14-redesigning-codepen--sparkbox--codepen.md
**URL:** http://codepen.seesparkbox.com/
**Category:** loading categories...
**Submitted by:** [@mrondina](http://twitter.com/mrondina)
An in progress report of codepen's redesign
=> Add resource: Redesigning CodePen | Sparkbox + CodePen

resources/_posts/2015-03-31-open-humans-wants-to-be-the-facebook-of-clinical-research--popular-science.md
**URL:** http://www.popsci.com/online-platform-open-humans-connects-clinical-trial-subjects-and-researchers
**Category:** inspiration
**Submitted by:** [@winterdamsel](http://twitter.com/winterdamsel)
After struggling a bit with finding interviewees for the first stage of our research, I am very glad to know about a project that implements the "open" concept in another way. 
For now, "Open Humans" is mostly aimed towards health projects and it's a bit limited since it just kicked off; however, it has a great potential for anyone with a project that involves people.
I'm actually excited about the fact that those (sometimes) long boring surveys have a chance to be revamped by awesome designers willing to contribute :)
=> Add resource: 'Open Humans' Wants To Be The Facebook Of Clinical Research | Popular Science

Rakefile
Fixes build errors and resolves #209
=> Make html-proofer use typhoeus

resources/_posts/2015-04-17-first-aid-git.md
**URL:** http://ricardofilipe.com/projects/firstaidgit/#/
**Category:** tutorials
**Submitted by:** [@una](http://twitter.com/una)
Quick answers to common Git problems.
=> Add resource: First Aid Git

resources/_posts/2015-04-22-wiry--the-open-source-wireframe-template.md
**URL:** http://usewiry.com/
**Category:** sources
**Submitted by:** [@simulo](http://twitter.com/simulo)
MIT licensed Wireframe Template
=> Add resource: Wiry – The Open Source Wireframe Template

resources/_posts/2015-04-17-first-aid-git.md, resources/_posts/2015-04-22-wiry--the-open-source-wireframe-template.md
This isn't final, but it seems like a good start.
=> Add Contributing.md file

resources/_posts/2015-04-23-why-you-should-design-for-open-source.md
**URL:** http://24ways.org/2014/why-you-should-design-for-open-source/
**Category:** philosophy
**Submitted by:** [@winterdamsel](http://twitter.com/winterdamsel)
Why make a portfolio just to demo your concepts when you can actually make them work? How about being a volunteer without leaving home?
=> Add resource: Why You Should Design for Open Source

resources/_posts/2015-04-26-git---the-simple-guide---no-deep-shit.md
**URL:** http://rogerdudler.github.io/git-guide/
**Category:** tutorials
**Submitted by:** [@una](http://twitter.com/una)
A simple guide to git
=> Add resource: git - the simple guide - no deep shit!

resources/_posts/usability-in-free-software--a-guide-by-jan-christoph-borchardt.md
Submitting a pull request manually because the resource collector extension failed me for some reason. :\
cc @GarthDB @una @terracomma please review. :)
=> add Usability in Free Software by @jancborchardt

resources/_posts/2015-05-10-designers-and-developers-no-longer-a-house-divided--smashing-magazine.md
**URL:** http://www.smashingmagazine.com/2015/05/08/designers-and-developers-no-longer-a-house-divided/
**Category:** philosophy
**Submitted by:** [@winterdamsel](http://twitter.com/winterdamsel)
It's not about mastering everything but, it's about collaborating and creating better things together. Plus, yeah, you get to learn cool stuff :)
=> Add resource: Designers And Developers: No Longer A House Divided – Smashing Magazine

CNAME
[#240] helping to move along to moving to [opendesign.foundation](http://opendesign.foundation)
=> Updated CNAME

resources/_posts/2015-06-15-brand-design-by-ryannpierce--pull-request-304--ef4liquid-fire.md
**URL:** https://github.com/ef4/liquid-fire/pull/304
**Category:** showcase
**Submitted by:** [@garthdb](http://twitter.com/garthdb)
Liquid Fire logo design on GitHub.
=> Add resource: Brand Design by ryannpierce · Pull Request #304 · ef4/liquid-fire

README.md
- _How To Contribute_ link was originally linking to the incorrect place
=> Fix Link In Read Me

resources/_posts/2015-03-3-wikiwand.md
**URL:** http://www.wikiwand.com/
**Category:** redesigns
**Submitted by:** [@NDoubles](http://twitter.com/NDoubles)
Wikipedia - Nicer.
=> Add resource: WikiWand

.github/PULL_REQUEST_TEMPLATE.md
Adding an introductory Pull Request Template. Very much open to feedback. What do you think is lacking?
=> Adding a Pull Request Template

_sass/_base.scss, _sass/_type.scss
I'm not really a fan of the yellow background. It's jarring to me. I also did some refactoring in the `_base.scss`.
=> Changing the style for links

resources/_posts/2016-04-30-git-smart-20-essential-tips-for-git-and-github-users--javaworld.md
**URL:** http://www.javaworld.com/article/2113465/developer-tools-ide/git-smart-20-essential-tips-for-git-and-github-users.html
**Category:** tutorials
**Submitted by:** [@una](http://twitter.com/una)
Great set of recommendation for Github
=> Add resource: Git smart! 20 essential tips for Git and GitHub users | JavaWorld
